# Generated by Django 4.2.5 on 2023-09-14 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('calories', models.IntegerField(default=0)),
                ('carbohydrates', models.IntegerField(default=0)),
                ('proteins', models.IntegerField(default=0)),
                ('fats', models.IntegerField(default=0)),
                ('recipe', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Dishes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeOffFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.dish')),
                ('special_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.specialfunction')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapi.typeofffood'),
        ),
    ]
