# Generated by Django 4.2.5 on 2023-09-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_alter_dish_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='recipe',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='specialfunction',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
