# Generated by Django 4.2.5 on 2023-09-16 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0003_alter_dish_recipe_alter_specialfunction_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webapi.typeofffood'),
        ),
    ]
