# Generated by Django 4.2.5 on 2023-09-16 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0004_alter_dish_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.typeofffood'),
        ),
        migrations.AlterField(
            model_name='specialfunction',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='typeofffood',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
