# Generated by Django 4.2.5 on 2023-09-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0005_alter_dish_type_alter_specialfunction_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='carbohydrates',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='fats',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='proteins',
        ),
    ]
