# Generated by Django 4.2.5 on 2023-09-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0006_remove_dish_calories_remove_dish_carbohydrates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='carbohydrates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='fats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dish',
            name='proteins',
            field=models.IntegerField(default=0),
        ),
    ]
