# Generated by Django 4.2.5 on 2023-09-16 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0007_dish_calories_dish_carbohydrates_dish_fats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.dish')),
            ],
            options={
                'verbose_name_plural': 'Order Dishes',
                'ordering': ['dish'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishes', models.ManyToManyField(to='webapi.orderdish')),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'ordering': ['id'],
            },
        ),
    ]
