# Generated by Django 4.2.5 on 2023-09-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0009_special_function'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='special_function',
            new_name='Special_menu_for_children',
        ),
        migrations.AlterModelOptions(
            name='special_menu_for_children',
            options={'ordering': ['title'], 'verbose_name_plural': 'Menu for children'},
        ),
    ]
