# Generated by Django 4.2.5 on 2023-09-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0010_rename_special_function_special_menu_for_children_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Special_menu_for_children',
        ),
    ]
