# Generated by Django 4.2.5 on 2023-09-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0011_delete_special_menu_for_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='carbohydrates',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dish',
            name='fats',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dish',
            name='proteins',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='SpecialFunction',
        ),
    ]
